spring:
  application:
    name: snapshot-helper
  docker:
    compose:
      enabled: false

server:
  port: 18000

logging:
  level:
    root: debug

cloud:
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}
      region: ${AWS_S3_REGION}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}