spring:
  application:
    name: snapshot-helper
  docker:
    compose:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

server:
  port: 18000

logging:
  level:
    root: debug

cloud:
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}
      region: ${AWS_S3_REGION}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}

notifier:
  slack:
    bot-token: ${SLACK_BOT_TOKEN}
    channel-id: ${SLACK_CHANNEL_ID}
resource:
  buffer-size-in-byte: 6291456 # 6 MB
